version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: vms_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: vms_db
      POSTGRES_USER: vms_user
      POSTGRES_PASSWORD: vms_password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./apps/backend/src/db/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./apps/backend/src/db/seed.sql:/docker-entrypoint-initdb.d/02-seed.sql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U vms_user -d vms_db']
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: vms_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    entrypoint: >
      /bin/sh -c "cp /tmp/pgpass /var/lib/pgadmin/pgpass && chmod 600 /var/lib/pgadmin/pgpass && /entrypoint.sh"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./infra/pgadmin/servers.json:/pgadmin4/servers.json:ro
      - ./infra/pgadmin/pgpass:/tmp/pgpass:ro
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:
